apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-wordpress
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-mysql
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
