apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.name "-mysql" | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.name | quote }}
    tier: mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.name | quote }}
    tier: frontend
  type: LoadBalancer
