apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: eks-course-efs
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: eks-course-efs
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
